### ISSUE TITLE
Deprecate updateStackToolState() 

### ISSUE THREAD

**Issue by ronzim** [dvisionlab/Larvitar#149]
Use csToolsUpdateImageIndex() instead, check for breaking changes

**Comment by daron1337** [comment]
`updateStackToolState` is generally preferred because uses imageIndex instead of the imageId in the form xxxxxx//:imageIndex.
Usually from UI you have access to imageIndex (eg sliceId)

**Comment by ronzim** [comment]
After checking around for different usages, this is my proposal:
