### ISSUE TITLE
Nrrd image is displayed corrupted

### ISSUE THREAD

**Issue by gkv311** [dvisionlab/Larvitar#156]
Reading NRRD volume data with sizes like `240x256x24@int16` or `480x512x24@int16` leads to corrupted view.

![image](https://user-images.githubusercontent.com/851453/125686259-90029507-0aa1-4818-bb9d-25028eccf25c.png)

I have prepared data samples based on `example.nrrd` coming with examples, so that to reproduce the issue it is needed to replace file within `docs/examples/nrrd.html`.

[example_240_256_24_short.zip](https://github.com/dvisionlab/Larvitar/files/6818689/example_240_256_24_short.zip)

**Comment by daron1337** [comment]
Thank you, we will take a look asap.
It seems a problem related to the custom nrrd loader.

**Comment by gkv311** [comment]
Thanks for fixing issue that fast!
