### ISSUE TITLE
window is not defined when try to run it in separated web worker

### ISSUE THREAD

**Issue by amr-rology** [dvisionlab/Larvitar#192]
When i'm try to run `resliceSeries()` in separated web worker i got this error from cornerstone 
window is not defined line: 11 

MY vue.config.js :
 configureWebpack: {
    output: {
      globalObject: "this",
    },
    plugins: [
      new WorkerPlugin({ globalObject: "this" }),
    ],
  }
  
  Any help please?

**Comment by daron1337** [comment]
reslice series is now deprecated
