### ISSUE TITLE
loading a segmentation mask on the image.

### ISSUE THREAD

**Issue by Maoweihang1995** [dvisionlab/Larvitar#193]
I am trying to import a nrrd file as a segmentation mask on the image.

And it is worked when the number of  frames of nrrd and dicom files are equal.But my dicom file and nrrd file have unequal frames, and when I try to import it, it doesn't work.
Can anyone tell me what to do

**Comment by daron1337** [comment]
Hello, the number of images of both volumes must be the same.
In alternative you can have the segmentation mask as a single mask for each dicom file.
