### ISSUE TITLE
Cornerstone tools

### ISSUE THREAD

**Issue by daron1337** [dvisionlab/Larvitar#78]
Refactor tools and add examples

**Comment by ronzim** [comment]
- [ ] update to latest version (5.1.3)
- [ ] check Cursors when nothing active (stay last one)
- [ ] check Delete tool

**Comment by zansa** [comment]
@ronzim allow to pass an elementId to the "setToolActive" and call "cornerstoneTools.setToolActiveForElement" (something like the "addTool" function)
