### ISSUE TITLE
Colormaps works only if delayed after render

### ISSUE THREAD

**Issue by ronzim** [dvisionlab/Larvitar#95]
Calling applyColormap after renderImage throws an error (viewport is undefined... maybe is not ready ?).
If delayed 500 ms it works correctly.

**Comment by daron1337** [comment]
RenderImage is async, you need to apply color map when larvitar_store.get("renderingStatus", elementId) is true

**Comment by ronzim** [comment]
Ok, todo: update docs

**Comment by daron1337** [comment]
Fixed
